### ISSUE TITLE
unmuteVolume does not work properly

### ISSUE THREAD

**Issue by Nastras** [bbriatte/homebridge-soundtouch-platform#4]
The unmute / mute works. What surprises me something that after switching from mute to unmute the volume does not change although in the Config in the config is set?
"unmuteVolume":20,

![](https://user-images.githubusercontent.com/27686185/57188213-26e68900-6efb-11e9-8b8d-5e6080c77ee8.png)

**Comment by bbriatte** [comment]
The unmute volume is unmute from 0 volume. the system go to 100% by default....

**Comment by Nastras** [comment]
You mean 100% of the previously set value?

I do not understand :-)

**Comment by bbriatte** [comment]
The problem with HomeKit, is when you mute the device with the slider from 20%, 10%, 5% 0% 
when unmuted the device after the light will be set to 100% because HomeKit don't known where you are
<img width="511" alt="Capture d’écran 2019-05-06 à 01 53 06" src="https://user-images.githubusercontent.com/9661124/57202117-be9eb280-6fa1-11e9-82c2-db55517bc6f9.png">

**Comment by Nastras** [comment]
Now I understand it. I did not think of the slider just to the switch.

Thats how it works.

Thanks!
